# Generated by Django 6.0 on 2025-12-11 19:31

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_raw', models.CharField(max_length=64)),
                ('datetime_iso_8601', models.CharField(max_length=64)),
                ('datetime_timezone', models.CharField(max_length=64)),
                ('datetime_parsed', models.DateTimeField(blank=True, null=True)),
                ('currency_primary', models.CharField(max_length=32)),
                ('currency_secondary', models.CharField(blank=True, max_length=16, null=True)),
                ('currency_exchange_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('currency_symbol', models.CharField(max_length=8)),
                ('store_name', models.CharField(max_length=255)),
                ('store_street', models.CharField(blank=True, max_length=255, null=True)),
                ('store_number', models.CharField(blank=True, max_length=64, null=True)),
                ('store_zip', models.CharField(blank=True, max_length=32, null=True)),
                ('store_city', models.CharField(max_length=255)),
                ('store_country', models.CharField(max_length=255)),
                ('total_subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('raw_entry', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=list)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='receipts.receipt')),
            ],
            options={
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['tags'], name='receipts_re_tags_b8f6f5_gin')],
            },
        ),
    ]
